# Generated by Django 4.2.4 on 2023-11-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='locations_proposed',
            new_name='locations_approved',
        ),
    ]
