# Generated by Django 4.2.4 on 2023-11-02 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_hint', models.CharField(choices=[('H', 'HOT'), ('C', 'COLD'), ('N', 'REQUEST HINT')], default='N', max_length=1)),
                ('hint_counter', models.IntegerField(default=0)),
                ('last_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_finished', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
