# Generated by Django 4.2.4 on 2023-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_activegame_points_for_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='activegame',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
