# Generated by Django 4.2.4 on 2023-12-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_activegame_is_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegame',
            name='curr_hint',
            field=models.CharField(choices=[('H', 'HOT'), ('C', 'COLD'), ('W', 'WARM'), ('CR', 'COOLER'), ('N', 'REQUEST HINT')], default='N', max_length=2),
        ),
    ]
