# Generated by Django 4.2.4 on 2023-12-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_alter_activegame_curr_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='starting_hint',
            field=models.CharField(default='', max_length=128),
        ),
    ]
