name: Django CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test

    - name: Set up Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku --version

    # - name: Log in to Heroku
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #   run: |
    #     echo -e "machine api.heroku.com\n  login $HEROKU_API_KEY" > ~/.netrc
    #     heroku container:login

    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        git fetch --all --unshallow
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/adv-software-dev-project.git
        git push heroku HEAD:main -f

